image_width: 640
image_height: 480
camera_name: arm_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [513.34301,   0.     , 307.89617,
           0.     , 513.84807, 244.62007,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.474424, 0.207336, -0.002361, 0.000427, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [401.35968,   0.     , 301.82931,   0.     ,
           0.     , 453.02356, 244.14869,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]